name: Get Modified Folders

on:
  push:
    branches:
      - master

jobs:
  get-modified-folders:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2


      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v37
  
      - name: List all changed files
        run: |
            for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
              echo "$file was changed"
            done

#       - name: Get modified folders
#         id: modified_folders
#         run: |
#           echo "Modified Folders:"
#           git diff --name-only ${{ github.event.before }} ${{ github.sha }} | awk -F'/' '{print $1}' | sort -u > modified_folders.txt

#       - name: Print modified folders
#         run: |
#           cat modified_folders.txt


      - name: Get modified folders
        run: |
            echo "Modified Folders:"
            git diff --name-only ${{ github.event.before }} ${{ github.sha }} | awk -F'/' 'NR==1{print $1; exit}' > modified_folders.txt
  
      - name: Print modified folders
        run: |
          cat modified_folders.txt
          
          
      - name: Zip folders and deploy 
        run: |
            while IFS= read -r folder; do
              folder_name=$(echo "$folder" | sed 's#/$##')
              zip -r "$folder_name.zip" "$folder_name"
              folder_size=$(du -ms "$folder_name" | awk '{print $1}')
              if [ "$folder_size" -gt 10 ]; then
                echo "folder size is greater than 10 mb"
              else 
                echo "folder size is less than 10 mb"
              fi
            done < modified_folders.txt
            
      - name: echoing folder name 
        run : echo $folder_name
