name: Get Modified Folders

on:
  push:
    branches:
      - master

jobs:
  get-modified-folders:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Get modified folders
        id: modified_folders
        run: |
          echo "Modified Folders:"
          git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep -E '^(src/)' > modified_folders.txt

      - name: Print modified folders
        run: |
          cat modified_folders.txt
