name: Get Modified Folders

on:
  push:
    branches:
      - master

jobs:
  get-modified-folders:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Get modified folders
        id: modified_folders
        run: |
          echo "Modified Folders:"
          git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep -E '^(src/)' > modified_folders.txt

      - name: Print modified folders
        run: |
          cat modified_folders.txt

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v37
  
      - name: List all changed files
        run: |
            for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
              echo "$file was changed"
            done